# This is a basic workflow to help you get started with Actions

name: test-action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push: {}
  pull_request: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-16.04
    if: github.event_name == 'push' || github.event.pull_request.base.repo.url != github.event.pull_request.head.repo.url
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: dump conditions
        run: |
          echo "isfork: ${{ github.event.pull_request.base.repo.url != github.event.pull_request.head.repo.url }}"
          echo "ispush: ${{ github.event_name == 'push' }}"
          echo "shouldrun: ${{ github.event_name == 'push' || github.event.pull_request.base.repo.url != github.event.pull_request.head.repo.url }}"
      - name: dump secret
        run: |
          echo secret:
          echo "${{ secrets.NOT_REALLY_SECRET }}"
          echo secret length:
          echo "${{ secrets.NOT_REALLY_SECRET }}" | wc -c
      - name: checkout default repo on push
        uses: actions/checkout@v2
        if: github.event_name == 'push'
      - name: checkout head repo on pull request
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Dump readme content
        run: cat README.md
      - run: |
          git status
          git checkout ${{ github.head_ref }}
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
